In [2]:
import torch
import plotly.express as px
import numpy as np
import pandas as pd
from torch.nn.functional import pad, relu

In [9]:
N = 2
x = torch.tensor([-1, 1.], dtype = torch.float).reshape((2, -1))
x

tensor([[-1.],
        [ 1.]])

In [10]:
W = 10
w = torch.arange(-W, W+1).reshape((1,-1))
w

tensor([[-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,
           4,   5,   6,   7,   8,   9,  10]])

In [15]:
diffs = w-x
l = torch.exp(-diffs**2)
l

tensor([[6.6397e-36, 1.6038e-28, 5.2429e-22, 2.3195e-16, 1.3888e-11, 1.1254e-07,
         1.2341e-04, 1.8316e-02, 3.6788e-01, 1.0000e+00, 3.6788e-01, 1.8316e-02,
         1.2341e-04, 1.1254e-07, 1.3888e-11, 2.3195e-16, 5.2429e-22, 1.6038e-28,
         6.6397e-36, 3.7835e-44, 0.0000e+00],
        [0.0000e+00, 3.7835e-44, 6.6397e-36, 1.6038e-28, 5.2429e-22, 2.3195e-16,
         1.3888e-11, 1.1254e-07, 1.2341e-04, 1.8316e-02, 3.6788e-01, 1.0000e+00,
         3.6788e-01, 1.8316e-02, 1.2341e-04, 1.1254e-07, 1.3888e-11, 2.3195e-16,
         5.2429e-22, 1.6038e-28, 6.6397e-36]])

In [21]:
A = l.sum((0))

In [22]:
A

tensor([6.6397e-36, 1.6038e-28, 5.2429e-22, 2.3195e-16, 1.3888e-11, 1.1254e-07,
        1.2341e-04, 1.8316e-02, 3.6800e-01, 1.0183e+00, 7.3576e-01, 1.0183e+00,
        3.6800e-01, 1.8316e-02, 1.2341e-04, 1.1254e-07, 1.3888e-11, 2.3195e-16,
        5.2429e-22, 1.6038e-28, 6.6397e-36])

In [24]:
px.scatter(A)

In [25]:
B = torch.zeros(2*W+1)
B[W] = 1
B[W+2] = 1

In [28]:
L = torch.norm(A-B)
L

tensor(1.6368)

In [26]:
px.scatter(A)
px.scatter(B)

In [18]:
W = 3
w = torch.arange(-W, W+1).reshape((1,-1))
bcoord = [-1, 1]
bmax = 1

N = 2
x = torch.tensor([[-4.1], [4.1]], dtype = torch.float, requires_grad=True)
optim = torch.optim.Adam([x], lr=1e-1)



In [20]:
losses = []
for i in range(1000):
    wmax = x.detach().abs().max().ceil().int().item()
    dmax = 1000*max(wmax, bmax)
    w = torch.arange(-dmax, dmax+1, dtype = torch.float)

    l = torch.exp(-10*(w-x)**2)
    A = l.sum((0))
    
    B = torch.zeros(2*dmax+1)
    for b in bcoord:
        B[dmax+b] = 1.
    L = torch.norm(A-B)
    optim.zero_grad()
    L.backward()
    optim.step()
    losses.append(L.item())
losses

tensor([[-4.5000],
        [ 4.5000]], requires_grad=True)

In [71]:
l = torch.exp(-(w-x)**2)
A = l.sum((0))
A


tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 3.7835e-44, 6.7089e-36, 1.6187e-28,
        5.2853e-22, 2.3356e-16, 1.3968e-11, 1.1305e-07, 1.2384e-04, 1.8358e-02,
        3.6843e-01, 1.0183e+00, 7.3491e-01, 1.0183e+00, 3.6843e-01, 1.8358e-02,
        1.2384e-04, 1.1305e-07, 1.3968e-11, 2.3356e-16, 5.2853e-22, 1.6187e-28,
        6.7089e-36, 3.7835e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       grad_fn=<SumBackward1>)

In [73]:
x = 21

In [4]:
W = 3
w = torch.arange(-W, W+1).reshape((1,-1))
bcoord = [-1, 1]
bmax = 1
f = torch.zeros((2*W+1,))
for i, bc in enumerate(bcoord):
    f[W+bc] = 1.

N = 2
x = torch.tensor([[-1], [1.]], dtype = torch.float, requires_grad=True)
optim = torch.optim.Adam([x], lr=1e-1)

tensor([0., 0., 0.])