In [1]:
import torch
import plotly.express as px
import numpy as np
import pandas as pd
from torch.nn.functional import pad, relu

In [9]:
N = 2
x = torch.tensor([-1, 1.], dtype = torch.float).reshape((2, -1))
x

tensor([[-1.],
        [ 1.]])

In [10]:
W = 10
w = torch.arange(-W, W+1).reshape((1,-1))
w

tensor([[-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,
           4,   5,   6,   7,   8,   9,  10]])

In [15]:
diffs = w-x
l = torch.exp(-diffs**2)
l

tensor([[6.6397e-36, 1.6038e-28, 5.2429e-22, 2.3195e-16, 1.3888e-11, 1.1254e-07,
         1.2341e-04, 1.8316e-02, 3.6788e-01, 1.0000e+00, 3.6788e-01, 1.8316e-02,
         1.2341e-04, 1.1254e-07, 1.3888e-11, 2.3195e-16, 5.2429e-22, 1.6038e-28,
         6.6397e-36, 3.7835e-44, 0.0000e+00],
        [0.0000e+00, 3.7835e-44, 6.6397e-36, 1.6038e-28, 5.2429e-22, 2.3195e-16,
         1.3888e-11, 1.1254e-07, 1.2341e-04, 1.8316e-02, 3.6788e-01, 1.0000e+00,
         3.6788e-01, 1.8316e-02, 1.2341e-04, 1.1254e-07, 1.3888e-11, 2.3195e-16,
         5.2429e-22, 1.6038e-28, 6.6397e-36]])

In [21]:
A = l.sum((0))

In [22]:
A

tensor([6.6397e-36, 1.6038e-28, 5.2429e-22, 2.3195e-16, 1.3888e-11, 1.1254e-07,
        1.2341e-04, 1.8316e-02, 3.6800e-01, 1.0183e+00, 7.3576e-01, 1.0183e+00,
        3.6800e-01, 1.8316e-02, 1.2341e-04, 1.1254e-07, 1.3888e-11, 2.3195e-16,
        5.2429e-22, 1.6038e-28, 6.6397e-36])

In [24]:
px.scatter(A)

In [25]:
B = torch.zeros(2*W+1)
B[W] = 1
B[W+2] = 1

In [28]:
L = torch.norm(A-B)
L

tensor(1.6368)

In [26]:
px.scatter(A)
px.scatter(B)

In [52]:
W = 3
w = torch.arange(-W, W+1).reshape((1,-1))
bcoord = [-1, 1]
bmax = 1

N = 2
x = torch.tensor([[-1], [1.]], dtype = torch.float, requires_grad=True)
optim = torch.optim.Adam([x], lr=1e-1)



In [70]:
losses = []
for i in range(5000):
    wmax = x.detach().abs().max().ceil().int().item()
    dmax = max(10*wmax, 10*bmax)
    w = torch.arange(-dmax, dmax+1, dtype = torch.float)

    l = torch.exp(-10*(w-x)**2)
    A = l.sum((0))
    
    B = torch.zeros(2*dmax+1)
    for b in bcoord:
        B[dmax+b] = 1.
    L = torch.norm(A-B)
    optim.zero_grad()
    L.backward()
    optim.step()
    losses.append(L.item())
losses

[0.17286424338817596,
 0.45916983485221863,
 0.1780509501695633,
 0.1634596288204193,
 0.29190683364868164,
 0.014373543672263622,
 0.17526398599147797,
 0.19086728990077972,
 0.00187687820289284,
 0.13193033635616302,
 0.13618867099285126,
 0.0018287916900590062,
 0.08822499215602875,
 0.10418593883514404,
 0.004283519461750984,
 0.053222715854644775,
 0.0813935175538063,
 0.008383498527109623,
 0.028142940253019333,
 0.06235424429178238,
 0.01275558490306139,
 0.0122306440025568,
 0.045557502657175064,
 0.015996122732758522,
 0.0037325567100197077,
 0.031120644882321358,
 0.017327038571238518,
 0.00042857701191678643,
 0.01966002583503723,
 0.016833903267979622,
 0.00016889108519535512,
 0.010556850582361221,
 0.014058295637369156,
 0.0011337787145748734,
 0.005095397587865591,
 0.011129176244139671,
 0.002303565153852105,
 0.0019673730712383986,
 0.008101189509034157,
 0.003113736864179373,
 0.0004931427538394928,
 0.005453955382108688,
 0.00344177708029747,
 0.00011354596063029021,

In [71]:
l = torch.exp(-(w-x)**2)
A = l.sum((0))
A

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 3.7835e-44, 6.7089e-36, 1.6187e-28,
        5.2853e-22, 2.3356e-16, 1.3968e-11, 1.1305e-07, 1.2384e-04, 1.8358e-02,
        3.6843e-01, 1.0183e+00, 7.3491e-01, 1.0183e+00, 3.6843e-01, 1.8358e-02,
        1.2384e-04, 1.1305e-07, 1.3968e-11, 2.3356e-16, 5.2853e-22, 1.6187e-28,
        6.7089e-36, 3.7835e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       grad_fn=<SumBackward1>)

In [72]:
x

tensor([[-1.0006],
        [ 1.0006]], requires_grad=True)