In [3]:
import torch
import plotly.express as px
import numpy as np
import pandas as pd
from torch.nn.functional import pad, relu

In [4]:

# Create goal
B = torch.tensor([0, 1, 0, 1, 0])
x = torch.tensor([i-2.0 for i in range(len(B))])
radB = len(B)//2
# Create coordinate tensor

z = torch.tensor([-0.4, 2.1], requires_grad=True)

optim = torch.optim.Adam([z], lr=1e-1)

In [6]:
X, Z = torch.meshgrid(x,z)

c:\Users\joelw\OneDrive\Documents\Projects\Programming\Fourier-Photos-Python\venv\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [7]:
E = torch.pow(10,(-(X-Z).pow(2)))

In [5]:
E

tensor([[2.7542e-03, 1.5488e-17],
        [4.3652e-01, 2.4547e-10],
        [6.9183e-01, 3.8905e-05],
        [1.0965e-02, 6.1660e-02],
        [1.7378e-06, 9.7724e-01]], grad_fn=<PowBackward2>)

In [6]:
F = E.max(-1)[0]

In [7]:
F

tensor([0.0028, 0.4365, 0.6918, 0.0617, 0.9772], grad_fn=<MaxBackward0>)

In [8]:
l = ((B-F)**2).sum()

In [63]:
optim.zero_grad()
l.backward()
optim.step()


In [64]:
print(z)
print(z.grad)
print(l)

tensor([-0.5000,  2.2000], requires_grad=True)
tensor([ 3.1225, -0.2934])
tensor(2.6316, grad_fn=<SumBackward0>)


# Loop code

In [58]:
# Create goal
B = torch.tensor([0, 0, 0, 1, 0, 1, 0, 0, 0], dtype=torch.float32)
radB = len(B)//2
x = torch.tensor([i-radB for i in range(len(B))], dtype=torch.float32)

# Create coordinate tensor
k = 10
z = torch.tensor([-2.4, 1.], requires_grad=True)

optim = torch.optim.Adam([z], lr=1e-1)

In [59]:
losses = []
for i in range(100):
  X, Z = torch.meshgrid(x,z)
  E = torch.exp(-k*(X-Z).pow(2))
  F = E.max(-1)[0]
  l1 = ((B-F)**2).sum()
  l2 = (relu(-z-radB)+relu(z-radB)).sum()
  l= l1+l2
  optim.zero_grad()
  l.backward()
  optim.step()
  losses.append(l.item())
print('Z: ', z)
print('Grad: ', z.grad)
print('loss: ', l)
print('F: ', F)

Z:  tensor([-2.5005,  1.0000], requires_grad=True)
Grad:  tensor([-1.0120e-03,  1.4439e-33])
loss:  tensor(1.0135, grad_fn=<AddBackward0>)
F:  tensor([1.7025e-10, 8.2256e-02, 8.1914e-02, 1.6813e-10, 4.5400e-05, 1.0000e+00,
        4.5400e-05, 4.2484e-18, 8.1940e-40], grad_fn=<MaxBackward0>)


In [67]:
px.scatter(losses)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'variable=0<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '0',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=int64),
              'xaxis': 'x',
              'y': array([2.63162756, 2.26827121, 1.92535615, 1.63321233, 1.40790856, 1.24862838,
                          1.14582133, 1.08656096, 1.05785084, 1.04911923, 1.05271184, 1.06286466,
                          1.07477236, 1.0845052 , 1.0894599 , 1.08870029, 1.08284152, 1.07348967,
                          1.06257105, 1.05177295, 1.042238  , 1.03451824, 1.02870488, 1.02461624,
                          1.02196443, 1.02045822, 1.0198468 , 1.01992583, 1.02052307, 1.02148223,
                          1.02265167, 1.02388155, 1.02503026, 1.02597451, 1.02662265, 1.02692389,
                          1.02687156, 1.02649915, 1.0258702 , 1.02506566, 1.02417016, 1.02326107,
                          1.02240217, 1.02163994, 1.0210036 , 1.02050662, 1.02015007, 1.01992548,
                          1.01981711, 1.01980472, 1.01986527, 1.01997495, 1.02011037, 1.02025056,
                          1.02037787, 1.02047873, 1.02054429, 1.02057099, 1.02055931, 1.02051342,
                          1.02044046, 1.02034903, 1.02024817, 1.02014625, 1.02005076, 1.01996744,
                          1.01989985, 1.01985002, 1.01981795, 1.01980209, 1.01980007, 1.01980829,
                          1.01982343, 1.01984191, 1.01986051, 1.0198766 , 1.01988852, 1.01989496,
                          1.01989579, 1.0198915 , 1.01988292, 1.01987123, 1.01985788, 1.01984394,
                          1.01983106, 1.01981974, 1.0198108 , 1.01980448, 1.01980078, 1.01979935,
                          1.01979995, 1.01980174, 1.01980436, 1.01980722, 1.01980972, 1.01981163,
                          1.01981282, 1.01981306, 1.01981246, 1.01981115]),
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [24]:
def f(z, B, x = None, k=1.):
    xrad = (len(B)-1) /2 
    if x is None:
        x = torch.tensor([i-xrad for i in range(len(B))])
    X, Z = torch.meshgrid(x,z)
    E = torch.exp(-k*(X-Z).pow(2))
    F = E.mean(-1)
    l = ((B-F)**2).sum()
    l2 = relu(-z-xrad)+relu(z-xrad)
    return l+l2.sum()

In [31]:
# Create goal
B = torch.tensor([ 0,0,1,0,0])
xrad = (len(B)-1) /2 
x = torch.tensor([i-xrad for i in range(len(B))])
radB = len(B)//2
# Create coordinate tensor
k = 10

In [32]:
X = list()
L = list()
xrange = np.linspace(-xrad-3, xrad+3, 100)
for i, xcoord in enumerate(xrange):
    z = torch.tensor([xcoord], dtype=torch.float32)
    l = f(z, B, x, k=k)
    X.append(xcoord)
    L.append(l)

In [33]:
df = pd.DataFrame({'X':X, 'L':L})
px.line(df, x='X', y ='L')

In [ ]:
A = torch.tensor([1,2,3])